name: The Key

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-lastest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: 22
        script: |
          cd /home/the_key
          git fetch origin
          git checkout production
          git pull
          sudo npm install
          npm run build
            
